const GET_DATA_WEATHER = 'GET_DATA_WEATHER';
const GET_DATA_WEATHER_SUCCESS = 'GET_DATA_WEATHER_SUCCESS';

const IS_LOADING = 'IS_LOADING';

export default {
  GET_DATA_WEATHER,
  GET_DATA_WEATHER_SUCCESS,
  IS_LOADING,
};
